
/* Generated by Interface Builder */

#import <objc/Object.h>
#import <objc/List.h>
#import "Anchor.h"
#import "HyperAccess.h"

@interface TextToy:Object
{
    id	GreyLevel;
    id	TextEnd;
    id	TextStart;
    id	FixedWindow;
    id	ScrollWindow;
    
    Anchor 	*StartAnchor;
    Anchor	*EndAnchor;
    
    List * accesses;
}

- setGreyLevel:anObject;
- setTextEnd:anObject;
- setTextStart:anObject;
- setFixedWindow:anObject;
- setScrollWindow:anObject;

- Do_getStartLength:sender;
- Do_getSel:sender;
- Do_setBackgroundGray:sender;

//	File handling

//- open: sender;				/* Initialise a new window */
//- search: sender;

/*	Link handling:
*/
- linkToMark: sender;
- linkToNew: sender;
- unlink:sender;
- markSelected: sender;
- markAll: sender;
- followLink: sender;
- dump: sender;

//	Access manager function:

- registerAccess:(HyperAccess *)access;

@end
